### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by riesinger** [freecloudio/meta#1]
We should really start designing a logo for the freecloudio org!

**Comment by lohluc** [comment]
Hi guys, I can help you with a logo 👋 (@slashmo asked me)

**Comment by riesinger** [comment]
So, here are some facts about Freecloud:

- We are free as in beer, freedom of speach and every other aspect of freedom (MIT or Apache license, we didn't decide yet)
- Our primary color is #274C77, see some others [here](https://coolors.co/274c77-ffffff-f8f8f8-f0506e-32d296)
- We are a file sharing, management and storage solution, like Owncloud or Nextcloud (whose icon I really like)
- We strive for **simplicity**. To us, Nextcloud is way to hard to install, manage and even use, therefore we want to provide a clean, understandable UI.
- We use [UIkit](https://getuikit.com) for our UI Framework
- We'll use [Material Design Icons](https://materialdesignicons.com) for file icons ect..

**Comment by riesinger** [comment]
@lohluc Hey, how's the logo doing? 🤔 😄 I'm sure it will look awesome! 🚀
