### ISSUE TITLE
We need docs!

### ISSUE THREAD

**Issue by riesinger** [freecloudio/meta#4]
We should really start to get into some sort of Server API docs and Web client dev docs.

**Comment by riesinger** [comment]
@TheHamloer Do you have any idea as to what documentation system to use?

List of possible systems

Platform | Adv. | Disadv.
--- | --- | ---
[Swagger](https://swagger.io/) | **Heavy** focus on APIs | ONLY APIs
[Hugo](https://gohugo.io) | Some nice themes like [docuapi](http://docuapi.com/?go#get-a-specific-kitten), static deployment|-

**Comment by mheidinger** [comment]
So the docuapi looks good and would also have the possibility to include other docs than the API itself...
Is there any tool to generate some docs from the go code itself for internal docs?

**Comment by riesinger** [comment]
Well, there is godoc, which is powering [godoc.org](https://godoc.org), which is baked into the tooling.
However, This is not a nice way of documenting an API I think

**Comment by mheidinger** [comment]
Ah no not for an API.... But I guess an internal one wouldn't be included in an official doc

**Comment by riesinger** [comment]
The API docs are now located at `freecloudio.github.io/freecloud`
